import CWType.SimpleGraph.CaroWeiType.Basic
import CWType.SimpleGraph.CaroWeiType.Degenerate
import CWType.SimpleGraph.CaroWeiType.IndepSet
import CWType.SimpleGraph.CaroWeiType.BoundedDegreeCaterpillars.ABCLemma
